// Regional identities are inspired by real vineyards. Numeric traits are game balance,
// not agronomic measurements or appellation planting rules.
export type Variety = string;
export type Grape = {
  name: string;
  color: string;
  wineType: 'Red' | 'White';
  planting: number;
  preferred: string;
  note: string;
  heat: number;
  resilience: number;
  finesse: number;
  yieldFactor: number;
  collection: 'classic' | 'heritage' | 'discovery';
};
function grape(
  name: string,
  wineType: Grape['wineType'],
  planting: number,
  preferred: string,
  heat: number,
  resilience: number,
  finesse: number,
  note: string,
  collection: Grape['collection'] = 'classic',
  yieldFactor = 1,
): Grape {
  return {
    name,
    wineType,
    color: wineType === 'White' ? '#aaa164' : '#87576e',
    planting,
    preferred,
    heat,
    resilience,
    finesse,
    note,
    collection,
    yieldFactor,
  };
}
export const VARIETIES: Record<string, Grape> = {
  merlot: grape(
    'Merlot',
    'Red',
    650,
    'Clay',
    3,
    3,
    0,
    'Plush plum fruit and a generous, rounded style.',
  ),
  chardonnay: grape(
    'Chardonnay',
    'White',
    550,
    'Limestone',
    2,
    3,
    0,
    'Versatile whites, from bright citrus to orchard fruit.',
  ),
  pinot: grape(
    'Pinot Noir',
    'Red',
    850,
    'Chalk',
    1,
    1,
    4,
    'Fragrant red fruit. Delicate vines reward careful tending.',
    'classic',
    0.92,
  ),
  cabernet: grape(
    'Cabernet Sauvignon',
    'Red',
    850,
    'Gravel',
    4,
    4,
    2,
    'Structured blackcurrant reds that welcome a long, warm season.',
  ),
  sauvignon: grape(
    'Sauvignon Blanc',
    'White',
    650,
    'Limestone',
    2,
    3,
    1,
    'Fresh citrus, herbs, and lively aromatic whites.',
  ),
  syrah: grape(
    'Syrah / Shiraz',
    'Red',
    750,
    'Granite',
    4,
    4,
    1,
    'Dark fruit and pepper; generous in warm vineyards.',
  ),
  riesling: grape(
    'Riesling',
    'White',
    700,
    'Slate',
    1,
    4,
    3,
    'Floral, bright whites with a cool-climate affinity.',
    'heritage',
    0.95,
  ),
  sangiovese: grape(
    'Sangiovese',
    'Red',
    750,
    'Limestone',
    3,
    3,
    2,
    'Sour cherry and savory character from sunlit hills.',
    'heritage',
  ),
  tempranillo: grape(
    'Tempranillo',
    'Red',
    700,
    'Clay',
    3,
    3,
    2,
    'Cherry fruit and structure, with a Spanish heritage.',
    'heritage',
  ),
  malbec: grape(
    'Malbec',
    'Red',
    750,
    'Alluvial',
    3,
    3,
    2,
    'Violet-scented, deeply colored reds.',
    'heritage',
  ),
  grenache: grape(
    'Grenache / Garnacha',
    'Red',
    650,
    'Sand',
    5,
    5,
    0,
    'Juicy red fruit from vines comfortable in heat.',
    'heritage',
    1.06,
  ),
  cabernet_franc: grape(
    'Cabernet Franc',
    'Red',
    700,
    'Clay',
    2,
    3,
    2,
    'Fragrant raspberry and herbal lift.',
    'heritage',
  ),
  semillon: grape(
    'Sémillon',
    'White',
    550,
    'Gravel',
    3,
    2,
    1,
    'Round, textured whites with honeyed character.',
    'heritage',
    1.04,
  ),
  aligote: grape(
    'Aligoté',
    'White',
    500,
    'Limestone',
    1,
    4,
    0,
    'Crisp, refreshing whites with a Burgundian heritage.',
    'heritage',
    1.05,
  ),
  zinfandel: grape(
    'Zinfandel',
    'Red',
    700,
    'Gravel',
    4,
    3,
    1,
    'Brambly, exuberant reds suited to sunny sites.',
    'heritage',
    1.04,
  ),
  viura: grape(
    'Viura',
    'White',
    550,
    'Limestone',
    3,
    3,
    1,
    'Fresh, subtle whites with room to develop in the cellar.',
    'heritage',
    1.05,
  ),
  torrontes: grape(
    'Torrontés',
    'White',
    650,
    'Alluvial',
    3,
    3,
    1,
    'Floral, aromatic whites inspired by Argentina.',
    'discovery',
  ),
  mourvedre: grape(
    'Mourvèdre / Mataro',
    'Red',
    800,
    'Sand',
    5,
    5,
    2,
    'Dark, savory reds from a heat-loving vine.',
    'discovery',
    0.95,
  ),
  petit_verdot: grape(
    'Petit Verdot',
    'Red',
    900,
    'Gravel',
    5,
    3,
    4,
    'Intense color and structure. Needs warmth to ripen.',
    'discovery',
    0.9,
  ),
  nebbiolo: grape(
    'Nebbiolo',
    'Red',
    950,
    'Limestone',
    3,
    2,
    5,
    'Rose, red fruit, and firm structure. A demanding estate project.',
    'discovery',
    0.88,
  ),
  chenin: grape(
    'Chenin Blanc',
    'White',
    650,
    'Chalk',
    2,
    4,
    2,
    'Apple, quince, and lively acidity.',
    'discovery',
  ),
  gewurztraminer: grape(
    'Gewürztraminer',
    'White',
    750,
    'Clay',
    2,
    2,
    3,
    'Aromatic whites with rose and spice.',
    'discovery',
    0.94,
  ),
  vermentino: grape(
    'Vermentino',
    'White',
    600,
    'Granite',
    4,
    5,
    1,
    'Citrus-led whites at home in sunny, dry settings.',
    'discovery',
  ),
  barbera: grape(
    'Barbera',
    'Red',
    650,
    'Clay',
    3,
    4,
    1,
    'Bright, juicy reds with a generous crop.',
    'discovery',
    1.08,
  ),
};
export const REGION_IDS = [
  'bordeaux',
  'burgundy',
  'napa',
  'mosel',
  'tuscany',
  'rioja',
  'mendoza',
  'barossa',
] as const;
export type RegionId = (typeof REGION_IDS)[number];
export type Region = {
  name: string;
  country: string;
  climate: string;
  heat: number;
  description: string;
  signature: string[];
  starters: [string, string];
  soils: [string, string, string, string, string, string];
  sky: string;
  hill: string;
  ground: string;
  landmark: 'chateau' | 'mountain' | 'river' | 'hills';
};
export const REGIONS: Record<RegionId, Region> = {
  bordeaux: {
    name: 'Bordeaux',
    country: 'France',
    climate: 'Temperate maritime',
    heat: 3,
    description:
      'Gravel terraces, clay soils, and an Atlantic breeze. Build an estate around generous reds and fresh whites.',
    signature: [
      'merlot',
      'cabernet',
      'cabernet_franc',
      'semillon',
      'sauvignon',
    ],
    starters: ['merlot', 'sauvignon'],
    soils: ['Clay', 'Limestone', 'Gravel', 'Gravel', 'Clay', 'Limestone'],
    sky: '#e5e8d5',
    hill: '#b7c59b',
    ground: '#d3d9b5',
    landmark: 'chateau',
  },
  burgundy: {
    name: 'Burgundy',
    country: 'France',
    climate: 'Cool continental',
    heat: 1,
    description:
      'A patchwork of limestone slopes. Patient care turns delicate Pinot Noir and Chardonnay into expressive wines.',
    signature: ['pinot', 'chardonnay', 'aligote'],
    starters: ['pinot', 'chardonnay'],
    soils: ['Chalk', 'Limestone', 'Clay', 'Chalk', 'Clay', 'Limestone'],
    sky: '#e2e8dc',
    hill: '#a8b796',
    ground: '#d3d7b6',
    landmark: 'hills',
  },
  napa: {
    name: 'Napa Valley',
    country: 'United States',
    climate: 'Warm, with cool nights',
    heat: 4,
    description:
      'Sunlit valley floors beneath wooded ridges. Cabernet anchors the estate, with room for bold experiments.',
    signature: ['cabernet', 'chardonnay', 'zinfandel', 'sauvignon'],
    starters: ['cabernet', 'chardonnay'],
    soils: ['Gravel', 'Limestone', 'Clay', 'Gravel', 'Alluvial', 'Granite'],
    sky: '#efe6cd',
    hill: '#a5b18a',
    ground: '#d8cba0',
    landmark: 'mountain',
  },
  mosel: {
    name: 'Mosel',
    country: 'Germany',
    climate: 'Cool river valley',
    heat: 1,
    description:
      'Slate terraces above a winding river. Riesling thrives here; warmth-loving grapes will ask more of your skill.',
    signature: ['riesling', 'pinot'],
    starters: ['riesling', 'pinot'],
    soils: ['Slate', 'Chalk', 'Gravel', 'Slate', 'Alluvial', 'Limestone'],
    sky: '#dce7e4',
    hill: '#9caf9d',
    ground: '#c7d1ba',
    landmark: 'river',
  },
  tuscany: {
    name: 'Tuscany',
    country: 'Italy',
    climate: 'Sunny Mediterranean',
    heat: 3,
    description:
      'Rolling hills, limestone, and cypress-lined lanes. Sangiovese leads, with international grapes ready to explore.',
    signature: ['sangiovese', 'merlot', 'cabernet', 'vermentino'],
    starters: ['sangiovese', 'merlot'],
    soils: ['Limestone', 'Clay', 'Granite', 'Limestone', 'Clay', 'Sand'],
    sky: '#f0e5cf',
    hill: '#b3b78b',
    ground: '#d8cba3',
    landmark: 'hills',
  },
  rioja: {
    name: 'Rioja',
    country: 'Spain',
    climate: 'Continental, Atlantic influence',
    heat: 3,
    description:
      'Clay-limestone slopes and open skies. Tempranillo, Garnacha, and Viura offer different paths for your cellar.',
    signature: ['tempranillo', 'grenache', 'viura'],
    starters: ['tempranillo', 'viura'],
    soils: ['Clay', 'Limestone', 'Sand', 'Limestone', 'Alluvial', 'Clay'],
    sky: '#eee0ce',
    hill: '#b6b18c',
    ground: '#d7c4a5',
    landmark: 'hills',
  },
  mendoza: {
    name: 'Mendoza',
    country: 'Argentina',
    climate: 'Sunny high-altitude valley',
    heat: 3,
    description:
      'Andean peaks, alluvial soils, and cool nights. Start with Malbec and an aromatic white, then shape your own style.',
    signature: ['malbec', 'cabernet', 'torrontes'],
    starters: ['malbec', 'torrontes'],
    soils: ['Alluvial', 'Alluvial', 'Gravel', 'Limestone', 'Sand', 'Clay'],
    sky: '#e1e8e7',
    hill: '#a9b7ad',
    ground: '#d4c9aa',
    landmark: 'mountain',
  },
  barossa: {
    name: 'Barossa',
    country: 'Australia',
    climate: 'Warm and dry',
    heat: 5,
    description:
      'Golden hills and a long, sunny season. Shiraz, Grenache, and Mataro make natural companions in the vineyard.',
    signature: ['syrah', 'grenache', 'mourvedre', 'semillon'],
    starters: ['syrah', 'grenache'],
    soils: ['Granite', 'Sand', 'Clay', 'Gravel', 'Sand', 'Limestone'],
    sky: '#f1e3c9',
    hill: '#bab18b',
    ground: '#decca1',
    landmark: 'hills',
  },
};
export const RESEARCH_IDS = [
  'ampelography',
  'heritage',
  'adaptation',
  'breeding',
  'discovery',
  'selection',
] as const;
export type ResearchId = (typeof RESEARCH_IDS)[number];
export const RESEARCH: Record<
  ResearchId,
  {
    name: string;
    knowledge: number;
    cost: number;
    weeks: number;
    requires: ResearchId[];
    text: string;
  }
> = {
  ampelography: {
    name: 'Vine science',
    knowledge: 30,
    cost: 350,
    weeks: 2,
    requires: [],
    text: 'Learn to study grape varieties. Unlock the research tree and gain 2 extra knowledge each week.',
  },
  heritage: {
    name: 'Heritage collection',
    knowledge: 40,
    cost: 600,
    weeks: 3,
    requires: ['ampelography'],
    text: 'Open the nursery’s heritage collection: Riesling, Sangiovese, Tempranillo, Malbec, and six more.',
  },
  adaptation: {
    name: 'Climate adaptation',
    knowledge: 50,
    cost: 800,
    weeks: 3,
    requires: ['ampelography'],
    text: 'Reduce every grape’s climate mismatch by one level. Challenging imports become easier to grow.',
  },
  breeding: {
    name: 'Cross-pollination',
    knowledge: 55,
    cost: 900,
    weeks: 3,
    requires: ['ampelography'],
    text: 'Open your breeding nursery. Cross two varieties, select a trait, and develop an estate grape.',
  },
  discovery: {
    name: 'World collection',
    knowledge: 65,
    cost: 1000,
    weeks: 3,
    requires: ['heritage'],
    text: 'Unlock all 24 varieties, including Nebbiolo, Chenin Blanc, Vermentino, and Petit Verdot.',
  },
  selection: {
    name: 'Field selection',
    knowledge: 70,
    cost: 1100,
    weeks: 4,
    requires: ['breeding'],
    text: 'Add 2 resilience to every vine and shorten new breeding trials from 4 weeks to 3.',
  },
};
export const TRAITS = {
  climate: {
    name: 'Regional adaptation',
    text: 'Moves inherited warmth preference toward your region; slightly smaller crops.',
  },
  resilience: {
    name: 'Hardier vines',
    text: 'Adds 2 resilience above the parent average; trades away 1 finesse.',
  },
  finesse: {
    name: 'Wine quality',
    text: 'Adds 3 finesse above the parent average; smaller crops and more delicate vines.',
  },
} as const;
export type BreedingTrait = keyof typeof TRAITS;
