// Regional identities are inspired by real vineyards. Numeric traits are game balance,
// not agronomic measurements or appellation planting rules.
export type Variety = string;
export type Grape = {
  name: string;
  color: string;
  wineType: 'Red' | 'White';
  planting: number;
  preferred: string;
  note: string;
  heat: number;
  resilience: number;
  finesse: number;
  yieldFactor: number;
  collection: 'classic' | 'heritage' | 'discovery';
};
function grape(
  name: string,
  wineType: Grape['wineType'],
  planting: number,
  preferred: string,
  heat: number,
  resilience: number,
  finesse: number,
  note: string,
  collection: Grape['collection'] = 'classic',
  yieldFactor = 1,
): Grape {
  return {
    name,
    wineType,
    color: wineType === 'White' ? '#aaa164' : '#87576e',
    planting,
    preferred,
    heat,
    resilience,
    finesse,
    note,
    collection,
    yieldFactor,
  };
}
export const VARIETIES: Record<string, Grape> = {
  merlot: grape(
    'Merlot',
    'Red',
    650,
    'Clay',
    3,
    3,
    0,
    'Plush plum fruit and a generous, rounded style.',
  ),
  chardonnay: grape(
    'Chardonnay',
    'White',
    550,
    'Limestone',
    2,
    3,
    0,
    'Versatile whites, from bright citrus to orchard fruit.',
  ),
  pinot: grape(
    'Pinot Noir',
    'Red',
    850,
    'Chalk',
    1,
    1,
    4,
    'Fragrant red fruit. Delicate vines reward careful tending.',
    'classic',
    0.92,
  ),
  cabernet: grape(
    'Cabernet Sauvignon',
    'Red',
    850,
    'Gravel',
    4,
    4,
    2,
    'Structured blackcurrant reds that welcome a long, warm season.',
  ),
  sauvignon: grape(
    'Sauvignon Blanc',
    'White',
    650,
    'Limestone',
    2,
    3,
    1,
    'Fresh citrus, herbs, and lively aromatic whites.',
  ),
  syrah: grape(
    'Syrah / Shiraz',
    'Red',
    750,
    'Granite',
    4,
    4,
    1,
    'Dark fruit and pepper; generous in warm vineyards.',
  ),
  riesling: grape(
    'Riesling',
    'White',
    700,
    'Slate',
    1,
    4,
    3,
    'Floral, bright whites with a cool-climate affinity.',
    'heritage',
    0.95,
  ),
  sangiovese: grape(
    'Sangiovese',
    'Red',
    750,
    'Limestone',
    3,
    3,
    2,
    'Sour cherry and savory character from sunlit hills.',
    'heritage',
  ),
  tempranillo: grape(
    'Tempranillo',
    'Red',
    700,
    'Clay',
    3,
    3,
    2,
    'Cherry fruit and structure, with a Spanish heritage.',
    'heritage',
  ),
  malbec: grape(
    'Malbec',
    'Red',
    750,
    'Alluvial',
    3,
    3,
    2,
    'Violet-scented, deeply colored reds.',
    'heritage',
  ),
  grenache: grape(
    'Grenache / Garnacha',
    'Red',
    650,
    'Sand',
    5,
    5,
    0,
    'Juicy red fruit from vines comfortable in heat.',
    'heritage',
    1.06,
  ),
  cabernet_franc: grape(
    'Cabernet Franc',
    'Red',
    700,
    'Clay',
    2,
    3,
    2,
    'Fragrant raspberry and herbal lift.',
    'heritage',
  ),
  semillon: grape(
    'Sémillon',
    'White',
    550,
    'Gravel',
    3,
    2,
    1,
    'Round, textured whites with honeyed character.',
    'heritage',
    1.04,
  ),
  aligote: grape(
    'Aligoté',
    'White',
    500,
    'Limestone',
    1,
    4,
    0,
    'Crisp, refreshing whites with a Burgundian heritage.',
    'heritage',
    1.05,
  ),
  zinfandel: grape(
    'Zinfandel',
    'Red',
    700,
    'Gravel',
    4,
    3,
    1,
    'Brambly, exuberant reds suited to sunny sites.',
    'heritage',
    1.04,
  ),
  viura: grape(
    'Viura',
    'White',
    550,
    'Limestone',
    3,
    3,
    1,
    'Fresh, subtle whites with room to develop in the cellar.',
    'heritage',
    1.05,
  ),
  torrontes: grape(
    'Torrontés',
    'White',
    650,
    'Alluvial',
    3,
    3,
    1,
    'Floral, aromatic whites inspired by Argentina.',
    'discovery',
  ),
  mourvedre: grape(
    'Mourvèdre / Mataro',
    'Red',
    800,
    'Sand',
    5,
    5,
    2,
    'Dark, savory reds from a heat-loving vine.',
    'discovery',
    0.95,
  ),
  petit_verdot: grape(
    'Petit Verdot',
    'Red',
    900,
    'Gravel',
    5,
    3,
    4,
    'Intense color and structure. Needs warmth to ripen.',
    'discovery',
    0.9,
  ),
  nebbiolo: grape(
    'Nebbiolo',
    'Red',
    950,
    'Limestone',
    3,
    2,
    5,
    'Rose, red fruit, and firm structure. A demanding estate project.',
    'discovery',
    0.88,
  ),
  chenin: grape(
    'Chenin Blanc',
    'White',
    650,
    'Chalk',
    2,
    4,
    2,
    'Apple, quince, and lively acidity.',
    'discovery',
  ),
  gewurztraminer: grape(
    'Gewürztraminer',
    'White',
    750,
    'Clay',
    2,
    2,
    3,
    'Aromatic whites with rose and spice.',
    'discovery',
    0.94,
  ),
  vermentino: grape(
    'Vermentino',
    'White',
    600,
    'Granite',
    4,
    5,
    1,
    'Citrus-led whites at home in sunny, dry settings.',
    'discovery',
  ),
  barbera: grape(
    'Barbera',
    'Red',
    650,
    'Clay',
    3,
    4,
    1,
    'Bright, juicy reds with a generous crop.',
    'discovery',
    1.08,
  ),
  gamay: grape(
    'Gamay',
    'Red',
    600,
    'Granite',
    1,
    3,
    1,
    'Bright berry fruit and a light, lively style. A friendly partner for Pinot Noir.',
    'classic',
    1.08,
  ),
  carmenere: grape(
    'Carménère',
    'Red',
    850,
    'Clay',
    4,
    3,
    3,
    'Dark fruit, herbs, and spice. A patient warm-site project with a Chilean identity.',
    'discovery',
    0.94,
  ),
  graciano: grape(
    'Graciano',
    'Red',
    900,
    'Limestone',
    3,
    4,
    3,
    'Aromatic intensity and lively acidity. Small crops bring detail to Tempranillo blends.',
    'heritage',
    0.86,
  ),
  petite_sirah: grape(
    'Petite Sirah / Durif',
    'Red',
    850,
    'Gravel',
    4,
    4,
    2,
    'Inky color and firm tannins. Adds muscle to Zinfandel; distinct from Syrah.',
    'heritage',
    0.96,
  ),
  pinot_gris: grape(
    'Pinot Gris / Pinot Grigio',
    'White',
    600,
    'Clay',
    2,
    3,
    1,
    'Pear and orchard fruit, with a rounded texture and a flexible cellar style.',
    'classic',
    1.03,
  ),
  viognier: grape(
    'Viognier',
    'White',
    750,
    'Granite',
    4,
    2,
    3,
    'Apricot and floral perfume. Delicate vines; a small addition can lift a Syrah blend.',
    'heritage',
    0.92,
  ),
  albarino: grape(
    'Albariño',
    'White',
    750,
    'Granite',
    2,
    4,
    3,
    'Citrus and stone fruit with a fresh Atlantic character inspired by Rías Baixas.',
    'discovery',
    0.96,
  ),
  gruner_veltliner: grape(
    'Grüner Veltliner',
    'White',
    700,
    'Alluvial',
    2,
    4,
    2,
    'Crisp orchard fruit and white-pepper character, with an Austrian heritage.',
    'discovery',
    1.05,
  ),
  marsanne: grape(
    'Marsanne',
    'White',
    700,
    'Granite',
    4,
    3,
    2,
    'Rounded pear and nutty depth. Supplies texture to a Rhône-style white blend.',
    'heritage',
    1.04,
  ),
  roussanne: grape(
    'Roussanne',
    'White',
    900,
    'Limestone',
    3,
    1,
    4,
    'Fragrant, finely textured whites. Demanding vines reward care and complement Marsanne.',
    'discovery',
    0.88,
  ),
};

// Freeze the collection promised by saves before individual grape research.
// New catalog additions must still be studied in those estates.
export const LEGACY_VARIETY_IDS: readonly string[] = [
  'merlot',
  'chardonnay',
  'pinot',
  'cabernet',
  'sauvignon',
  'syrah',
  'riesling',
  'sangiovese',
  'tempranillo',
  'malbec',
  'grenache',
  'cabernet_franc',
  'semillon',
  'aligote',
  'zinfandel',
  'viura',
  'torrontes',
  'mourvedre',
  'petit_verdot',
  'nebbiolo',
  'chenin',
  'gewurztraminer',
  'vermentino',
  'barbera',
];
export const REGION_IDS = [
  'bordeaux',
  'burgundy',
  'napa',
  'mosel',
  'tuscany',
  'rioja',
  'mendoza',
  'barossa',
] as const;
export type RegionId = (typeof REGION_IDS)[number];
export type Region = {
  name: string;
  country: string;
  climate: string;
  heat: number;
  description: string;
  signature: string[];
  starters: [string, string];
  soils: [string, string, string, string, string, string];
  sky: string;
  hill: string;
  ground: string;
  landmark: 'chateau' | 'mountain' | 'river' | 'hills';
};
export const REGIONS: Record<RegionId, Region> = {
  bordeaux: {
    name: 'Bordeaux',
    country: 'France',
    climate: 'Temperate maritime',
    heat: 3,
    description:
      'Gravel terraces, clay soils, and an Atlantic breeze. Build an estate around generous reds and fresh whites.',
    signature: [
      'merlot',
      'cabernet',
      'cabernet_franc',
      'semillon',
      'sauvignon',
    ],
    starters: ['merlot', 'sauvignon'],
    soils: ['Clay', 'Limestone', 'Gravel', 'Gravel', 'Clay', 'Limestone'],
    sky: '#e5e8d5',
    hill: '#b7c59b',
    ground: '#d3d9b5',
    landmark: 'chateau',
  },
  burgundy: {
    name: 'Burgundy',
    country: 'France',
    climate: 'Cool continental',
    heat: 1,
    description:
      'A patchwork of limestone slopes. Patient care turns delicate Pinot Noir and Chardonnay into expressive wines.',
    signature: ['pinot', 'chardonnay', 'aligote', 'gamay'],
    starters: ['pinot', 'chardonnay'],
    soils: ['Chalk', 'Limestone', 'Clay', 'Chalk', 'Clay', 'Limestone'],
    sky: '#e2e8dc',
    hill: '#a8b796',
    ground: '#d3d7b6',
    landmark: 'hills',
  },
  napa: {
    name: 'Napa Valley',
    country: 'United States',
    climate: 'Warm, with cool nights',
    heat: 4,
    description:
      'Sunlit valley floors beneath wooded ridges. Cabernet anchors the estate, with room for bold experiments.',
    signature: [
      'cabernet',
      'chardonnay',
      'zinfandel',
      'sauvignon',
      'petite_sirah',
    ],
    starters: ['cabernet', 'chardonnay'],
    soils: ['Gravel', 'Limestone', 'Clay', 'Gravel', 'Alluvial', 'Granite'],
    sky: '#efe6cd',
    hill: '#a5b18a',
    ground: '#d8cba0',
    landmark: 'mountain',
  },
  mosel: {
    name: 'Mosel',
    country: 'Germany',
    climate: 'Cool river valley',
    heat: 1,
    description:
      'Slate terraces above a winding river. Riesling thrives here; warmth-loving grapes will ask more of your skill.',
    signature: ['riesling', 'pinot'],
    starters: ['riesling', 'pinot'],
    soils: ['Slate', 'Chalk', 'Gravel', 'Slate', 'Alluvial', 'Limestone'],
    sky: '#dce7e4',
    hill: '#9caf9d',
    ground: '#c7d1ba',
    landmark: 'river',
  },
  tuscany: {
    name: 'Tuscany',
    country: 'Italy',
    climate: 'Sunny Mediterranean',
    heat: 3,
    description:
      'Rolling hills, limestone, and cypress-lined lanes. Sangiovese leads, with international grapes ready to explore.',
    signature: ['sangiovese', 'merlot', 'cabernet', 'vermentino'],
    starters: ['sangiovese', 'merlot'],
    soils: ['Limestone', 'Clay', 'Granite', 'Limestone', 'Clay', 'Sand'],
    sky: '#f0e5cf',
    hill: '#b3b78b',
    ground: '#d8cba3',
    landmark: 'hills',
  },
  rioja: {
    name: 'Rioja',
    country: 'Spain',
    climate: 'Continental, Atlantic influence',
    heat: 3,
    description:
      'Clay-limestone slopes and open skies. Tempranillo, Garnacha, and Viura offer different paths for your cellar.',
    signature: ['tempranillo', 'grenache', 'viura', 'graciano'],
    starters: ['tempranillo', 'viura'],
    soils: ['Clay', 'Limestone', 'Sand', 'Limestone', 'Alluvial', 'Clay'],
    sky: '#eee0ce',
    hill: '#b6b18c',
    ground: '#d7c4a5',
    landmark: 'hills',
  },
  mendoza: {
    name: 'Mendoza',
    country: 'Argentina',
    climate: 'Sunny high-altitude valley',
    heat: 3,
    description:
      'Andean peaks, alluvial soils, and cool nights. Start with Malbec and an aromatic white, then shape your own style.',
    signature: ['malbec', 'cabernet', 'torrontes'],
    starters: ['malbec', 'torrontes'],
    soils: ['Alluvial', 'Alluvial', 'Gravel', 'Limestone', 'Sand', 'Clay'],
    sky: '#e1e8e7',
    hill: '#a9b7ad',
    ground: '#d4c9aa',
    landmark: 'mountain',
  },
  barossa: {
    name: 'Barossa',
    country: 'Australia',
    climate: 'Warm and dry',
    heat: 5,
    description:
      'Golden hills and a long, sunny season. Shiraz, Grenache, and Mataro make natural companions in the vineyard.',
    signature: [
      'syrah',
      'grenache',
      'mourvedre',
      'semillon',
      'viognier',
      'marsanne',
      'roussanne',
    ],
    starters: ['syrah', 'grenache'],
    soils: ['Granite', 'Sand', 'Clay', 'Gravel', 'Sand', 'Limestone'],
    sky: '#f1e3c9',
    hill: '#bab18b',
    ground: '#decca1',
    landmark: 'hills',
  },
};
export const RESEARCH_DEPARTMENTS = {
  vineyard: 'Vineyard science',
  cellar: 'Cellar techniques',
  hospitality: 'Tourism & hospitality',
  business: 'Commerce & discovery',
  grapes: 'Individual grapes',
} as const;
export type ResearchDepartment = keyof typeof RESEARCH_DEPARTMENTS;
export const TECHNIQUE_IDS = [
  'ampelography',
  'heritage',
  'soil_mapping',
  'adaptation',
  'precision_viticulture',
  'breeding',
  'selection',
  'backcrossing',
  'genomics',
  'oenology',
  'skin_contact',
  'malolactic',
  'lees_aging',
  'assemblage',
  'vintage_blending',
  'regional_blending',
  'rose_trials',
  'cellar_control',
  'fruit_selection',
  'cold_chain',
  'sensory_science',
  'tourism',
  'visitor_services',
  'hospitality',
  'sommelier_training',
  'culinary_tourism',
  'estate_lodging',
  'brand_strategy',
  'direct_sales',
  'export_trade',
  'discovery',
  'field_notebooks',
  'research_methods',
] as const;
export type TechniqueId = (typeof TECHNIQUE_IDS)[number];
export type ResearchId = TechniqueId | `grape_${string}`;
type Study = {
  name: string;
  knowledge: number;
  cost: number;
  weeks: number;
  requires: ResearchId[];
  text: string;
  department: ResearchDepartment;
  grape?: string;
};
const study = (
  department: ResearchDepartment,
  name: string,
  knowledge: number,
  cost: number,
  weeks: number,
  requires: ResearchId[],
  text: string,
): Study => ({ department, name, knowledge, cost, weeks, requires, text });
export const TECHNIQUES = {
  ampelography: study(
    'vineyard',
    'Vine science',
    40,
    1200,
    6,
    [],
    'Gain 2 knowledge each week. Opens individual studies of classic grapes and nursery propagation.',
  ),
  heritage: study(
    'vineyard',
    'Nursery propagation',
    80,
    4500,
    10,
    ['ampelography'],
    'Learn to establish imported vines. Opens individual heritage grape studies and cross-pollination; each grape needs its own study.',
  ),
  soil_mapping: study(
    'vineyard',
    'Soil & water mapping',
    90,
    7000,
    12,
    ['ampelography'],
    'Unlocks drip irrigation for purchase and the path to a specialist viticulture team.',
  ),
  adaptation: study(
    'vineyard',
    'Climate adaptation',
    160,
    14000,
    18,
    ['heritage'],
    'Reduce every grape’s climate mismatch by one level. Challenging imports become easier to grow.',
  ),
  precision_viticulture: study(
    'vineyard',
    'Precision viticulture',
    220,
    24000,
    24,
    ['soil_mapping', 'adaptation'],
    'Unlocks the viticulture team: faster growth and healthier vines across your holdings.',
  ),
  breeding: study(
    'vineyard',
    'Cross-pollination',
    220,
    22000,
    24,
    ['heritage'],
    'Open the breeding nursery. Cross two learned varieties in a separate 24-week, $7,500 field trial.',
  ),
  selection: study(
    'vineyard',
    'Field selection',
    440,
    65000,
    40,
    ['breeding', 'adaptation'],
    'Add 2 resilience to every vine. New breeding trials take 18 weeks instead of 24.',
  ),
  backcrossing: study(
    'vineyard',
    'Generational crosses',
    550,
    85000,
    52,
    ['selection'],
    'Use your own hybrid grapes as parents. Build a lineage over successive generations of field trials.',
  ),
  genomics: study(
    'vineyard',
    'Aroma & finesse selection',
    900,
    180000,
    72,
    ['backcrossing'],
    'Unlock the Wine quality breeding trait: finer grapes with smaller crops and more delicate vines.',
  ),
  oenology: study(
    'cellar',
    'Cellar foundations',
    35,
    1500,
    6,
    [],
    'Combine reserve lots of the same grape, vintage and estate. Single-lot bottling is available from the beginning.',
  ),
  skin_contact: study(
    'cellar',
    'Skin contact',
    55,
    2800,
    8,
    ['oenology'],
    'Unlock optional skin contact for each new batch: more body and tannin. Adds 1 week in the tanks and $40 per tank.',
  ),
  malolactic: study(
    'cellar',
    'Malolactic fermentation',
    85,
    6500,
    10,
    ['oenology'],
    'Unlock optional malolactic fermentation for a softer, rounder wine. Adds 2 weeks in the tanks and $60 per tank.',
  ),
  lees_aging: study(
    'cellar',
    'Lees aging',
    120,
    10000,
    12,
    ['oenology'],
    'Unlock optional rest on fine yeast sediment for fuller texture and bread-dough notes. Adds 3 weeks in the tanks and $50 per tank.',
  ),
  assemblage: study(
    'cellar',
    'Varietal assemblage',
    100,
    7500,
    14,
    ['oenology'],
    'Blend different grape varieties. Their proportions and compatibility determine the finished wine’s quality.',
  ),
  vintage_blending: study(
    'cellar',
    'Perpetual reserves',
    220,
    22000,
    26,
    ['assemblage'],
    'Blend across vintages, carrying older reserves into new releases. Keep your best lots for future years.',
  ),
  regional_blending: study(
    'cellar',
    'Regional cuvées',
    300,
    38000,
    30,
    ['assemblage', 'adaptation'],
    'Blend wine from different estates. Bring contrasting terroirs together in one release.',
  ),
  rose_trials: study(
    'cellar',
    'Red & white experiments',
    260,
    28000,
    24,
    ['assemblage'],
    'Combine red and white grape components. Permission to experiment does not guarantee a harmonious blend.',
  ),
  cellar_control: study(
    'cellar',
    'Fermentation control',
    110,
    9000,
    12,
    ['oenology'],
    'Unlocks the winemaker’s bench for purchase, adding temperature control to new fermentations.',
  ),
  fruit_selection: study(
    'cellar',
    'Selective fruit handling',
    180,
    18500,
    20,
    ['cellar_control'],
    'Unlocks the optical sorting line for purchase. Better fruit selection improves future harvest quality.',
  ),
  cold_chain: study(
    'cellar',
    'Cold-chain logistics',
    130,
    14000,
    18,
    ['oenology'],
    'Unlocks refrigerated grape storage for purchase, extending the time to process a harvest.',
  ),
  sensory_science: study(
    'cellar',
    'Sensory science',
    80,
    4500,
    10,
    ['oenology'],
    'Establish a formal tasting vocabulary. A prerequisite for training a professional sommelier team.',
  ),
  tourism: study(
    'hospitality',
    'Wine tourism',
    90,
    8500,
    12,
    [],
    'Unlocks a tasting terrace for purchase. Start welcoming visitors, then develop a destination estate.',
  ),
  visitor_services: study(
    'hospitality',
    'Visitor services',
    180,
    22000,
    22,
    ['tourism'],
    'Unlocks the visitor center for purchase. Plan arrivals, estate tours and a larger hospitality operation.',
  ),
  hospitality: study(
    'hospitality',
    'Hosted tastings',
    280,
    45000,
    32,
    ['visitor_services'],
    'Unlocks the tasting room for purchase. A visitor center must also be operating before you build it.',
  ),
  sommelier_training: study(
    'hospitality',
    'Sommelier training',
    380,
    60000,
    40,
    ['hospitality', 'sensory_science'],
    'Unlocks the sommelier team for hire: stronger demand and retail value for wines rated 80 or higher.',
  ),
  culinary_tourism: study(
    'hospitality',
    'Wine & gastronomy',
    500,
    95000,
    48,
    ['hospitality'],
    'Unlocks the estate restaurant for purchase. Dining can earn more per visitor, but quiet weeks still carry kitchen costs.',
  ),
  estate_lodging: study(
    'hospitality',
    'Destination stays',
    650,
    140000,
    60,
    ['culinary_tourism'],
    'Unlocks the vineyard guesthouse for purchase. Seasonal room bookings come with substantial ongoing maintenance.',
  ),
  brand_strategy: study(
    'business',
    'Estate storytelling',
    100,
    9000,
    14,
    [],
    'Develop your route to collectors and overseas buyers. Opens membership and export research.',
  ),
  direct_sales: study(
    'business',
    'Cellar-door membership',
    180,
    18000,
    20,
    ['brand_strategy', 'tourism'],
    'Unlocks the wine club team for hire. Older releases gain an audience when you keep them in stock.',
  ),
  export_trade: study(
    'business',
    'Export trade',
    400,
    60000,
    36,
    ['brand_strategy'],
    'Unlocks the export sales team for hire. Premium releases gain greater demand and wholesale value.',
  ),
  discovery: study(
    'business',
    'Experimental viticulture',
    240,
    28000,
    28,
    ['heritage', 'adaptation'],
    'Open individual studies of rare grapes. Each experimental variety has its own price and field-study duration.',
  ),
  field_notebooks: study(
    'business',
    'Field notebooks',
    120,
    12000,
    16,
    ['ampelography'],
    'Gain 4 additional knowledge each week through systematic vineyard observation.',
  ),
  research_methods: study(
    'business',
    'Research institute',
    500,
    80000,
    48,
    ['cellar_control', 'breeding'],
    'Unlocks the research & nursery lab for purchase. While operating, it doubles study and trial progress and adds 10 weekly knowledge.',
  ),
};
export const grapeResearchId = (id: string): ResearchId => `grape_${id}`;
export const GRAPE_STUDIES: Record<`grape_${string}`, Study> =
  Object.fromEntries(
    Object.entries(VARIETIES).map(([id, grape]) => {
      const tier = { classic: 0, heritage: 1, discovery: 2 }[grape.collection];
      return [
        grapeResearchId(id),
        {
          name: `${grape.name} field study`,
          department: 'grapes',
          grape: id,
          knowledge: 60 + tier * 70 + Math.max(0, grape.finesse) * 10,
          cost: Math.round(
            grape.planting * (6 + tier * 9) + Math.max(0, grape.finesse) * 650,
          ),
          weeks: 10 + tier * 8 + Math.max(0, grape.finesse) * 2,
          requires: [
            (['ampelography', 'heritage', 'discovery'] as const)[tier],
          ],
          text: `Learn to plant and breed ${grape.name}. This study unlocks this grape alone; planting still costs money.`,
        },
      ];
    }),
  );
export const RESEARCH: Record<ResearchId, Study> = {
  ...TECHNIQUES,
  ...GRAPE_STUDIES,
};
export const RESEARCH_IDS = Object.keys(RESEARCH) as [
  ResearchId,
  ...ResearchId[],
];
export const BREEDING = {
  cost: 7500,
  knowledge: 160,
  weeks: 24,
  selectedWeeks: 18,
};
export const TRAITS = {
  climate: {
    name: 'Regional adaptation',
    text: 'Moves inherited warmth preference toward your region; slightly smaller crops.',
  },
  resilience: {
    name: 'Hardier vines',
    text: 'Adds 2 resilience above the parent average; trades away 1 finesse.',
  },
  finesse: {
    name: 'Wine quality',
    text: 'Adds 3 finesse above the parent average; smaller crops and more delicate vines.',
  },
} as const;
export type BreedingTrait = keyof typeof TRAITS;
