export const PLOT_EXPANSION = {
  max: 4,
  step: 0.5,
  costPerHectare: 3000,
  upkeep: 15,
};
export const LAND = [
  {
    id: 1,
    name: 'South slope',
    soil: 'Clay',
    aspect: 'South-facing',
    area: '1.2',
    cost: 16800,
    yield: 360,
    x: 475,
    y: 262,
  },
  {
    id: 2,
    name: 'Limestone terrace',
    soil: 'Limestone',
    aspect: 'East-facing',
    area: '0.8',
    cost: 14000,
    yield: 280,
    x: 700,
    y: 377,
  },
  {
    id: 3,
    name: 'Orchard field',
    soil: 'Chalk',
    aspect: 'West-facing',
    area: '1.0',
    cost: 14000,
    yield: 310,
    x: 248,
    y: 378,
  },
  {
    id: 4,
    name: 'Hilltop parcel',
    soil: 'Chalk',
    aspect: 'South-facing',
    area: '1.4',
    cost: 16800,
    yield: 420,
    x: 708,
    y: 147,
  },
  {
    id: 5,
    name: 'River meadow',
    soil: 'Clay',
    aspect: 'East-facing',
    area: '1.1',
    cost: 14000,
    yield: 340,
    x: 475,
    y: 495,
  },
  {
    id: 6,
    name: 'Old stone field',
    soil: 'Limestone',
    aspect: 'West-facing',
    area: '1.3',
    cost: 19200,
    yield: 400,
    x: 245,
    y: 147,
  },
] as const;
export const plotScale = (expansions = 0) =>
  1 + expansions * PLOT_EXPANSION.step;
